# General settings (can be overwritten in file specific configs below)
[ settings ]
raw = "data/raw"
processed = "data/processed"
models = "models"

message_col = "message"
author_col = "author"
timestamp_col = "timestamp"

# Les 2
[ heatmaps ]
input.chat = "_chat.txt"
title = "Weekly Message Activity Heatmap"
xlabel = "Hour of Day"
ylabel = "Day of Week"
linewidths = 0.5
cmap = "YlGnBu"
yticks_ticks = [0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]
yticks_labels = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
cbar_kws = {'label' = 'Number of Messages'}
annot = true
fmt = "d"

# Les 3
[ worstenbroodjes ]
input.wikipedia_api = "https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/nl.wikipedia.org/all-access/user/Brabants_worstenbroodje/daily/20230101/20250311"
api_dt_format = "%Y%m%d%H"
request_headers = { 'User-Agent' = 'Marn-X/0.1 (marnix.ober@student.hu.nl)' }
json_nests = ["items"]
images = ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/North_Brabant-Flag.svg/1200px-North_Brabant-Flag.svg.png"]

# Les 4
[ hyperlinks_vs_genders ]
input.chat = "KJ.csv"
input.genders = "genders_distribution.json"
min_messages = 50
gender_colors = {"F" = "#AA336A", "M" = "#00008B"}

suptitle = "Vrouwen sturen in deze groepsapp minder hyperlinks dan mannen! (p = {p})"
title = "O.b.v. {num_m} mannen en {num_f} vrouwen in een groepsapp. Personen met minder dan {min_messages} berichten weggefilterd."
xlabel = "Percentage hyperlinks in verhouding tot verstuurde berichten"
ylabel = "Waarschijnlijkheidsdichtheid"

# Les 5
[ congratulations ]
suptitle = "Jongere familieleden feliciteren vaker dan ouderen in groepsapp. Wisselend verschil tussen mannen en vrouwen."
title = "Percentage berekend met verjaardagen die actieve gebruikers sinds hun eerst verstuurde bericht en nu meegemaakt hebben. Gebruiker heeft gefeliciteerd door op verjaardagen een bericht te sturen met RegEx: {congratulations_regex}"
xlabel = "Leeftijd familielid"
ylabel = "Percentage familieleden gefeliciteerd in groepsapp"
huelabel = "Geslacht"
input.chat = "steenvoorden.parq"
input.birthdates = "steenvoorden_geboortedata.json"
input.genders = "steenvoorden_geslachtdata.json"
min_messages = 10
birthday_dateformat = "%d-%m-%Y"
congratulations_regex = "(?ui)(gefelici|birthday|hbd|proficiat|🎉|🥳|🎊)"
congratulations_flags = "ui"

# Les 6
[ family_group_chat_topics ]
suptitle = "Familiegroepsapp vooral gebruikt voor status-updates. Clusters: reizen, felicitaties, medisch, weer."
title = "Gespreksonderwerpen opgehaald met 'sentence-embedding'. Dimensionaliteit verkleind met UMAP. BERT-model: {bert_sentence_model}"

# Set to false to train your own model!
use_pretrained_model = true
pretrained_model_name = "bertopic_robbert"

input.chat = "steenvoorden.parq"
# A list of stopwords is optional to better generate topics. If input contains multiple columns, the first column will be used as a list. Remove or comment out if not necessary.
input.stopwords = "https://raw.githubusercontent.com/stopwords-iso/stopwords-nl/refs/heads/master/stopwords-nl.txt"

# If applicable, a list of names that will be ignored for topics can be entered below. Case insensitive. Also takes Regex.
family_names = ['marnix', 'nikki', 'diane', 'jaap', 'gerrit', 'gytha', 'stefan', 'ruben', 'bente', 'marian', 'kees', 'opa', 'oma', "tante", "ome", 'mama?', 'papa?', 'yuki']

bert_sentence_model = "NetherlandsForensicInstitute/robbert-2022-dutch-sentence-transformers"
language = "dutch"
sentence_regex = '([^\.!?]*[\.!?])'
sentence_min_token_len = 4

# Dimensionality reduction with UMAP - Settings
umap_neighbors = 15
umap_n_components = 5
umap_min_dist = 0.0
umap_metric = "cosine"
umap_random_state = 42

# Clustering with HDBSCAN - Settings
hdbscan_min_cluster_size = 20
hdbscan_metric = "euclidean"
hdbscan_cluster_selection_method = "eom"
hdbscan_prediction_data = true

# Create topics with BERTopic - Settings
bertopic_top_n_words = 10
bertopic_verbose = true